### ISSUE TITLE
OpenSSL 1.1.x cleanup including TLS 1.3 support

### ISSUE THREAD

**Issue by samoht0** [RhythmLunatic/xdccget#3]
Nice to see you've forked this to do some enhancement.

I'm RPM packaging this and did investigate the ssl.c which involves OpenSSL 1.0.x methods and forces ciphers, that made sense in 2015, but not today.

What I did, was porting updates from upstream (r138 and r141), remove obsolete thread safety handling and update initialisation calls. I'm really far away from a OpenSSL expert, so this just my limited understanding of the documentation. As a matter of fact, at least TLS 1.3 connection work properly and compilation warning about unused functions are gone.

Maybe, you're interested to add this or something similar after a review.

[libircclient_OpenSSL11x_cleanup.patch.zip](https://github.com/RhythmLunatic/xdccget/files/5360850/libircclient_OpenSSL11x_cleanup.patch.zip)

**Comment by RhythmLunatic** [comment]
(Edit #3 because I didn't test enough and it does actually work)

I don't know a single thing about OpenSSL so I can't verify anything, but your patch does work and it still compiles and runs on Linux and Android (and probably Windows too). If you make a pull request I'll accept it, or if you don't care I'll just commit the patched file.

I tested with irc.rizon.net port 9999. As a side note ipv6 with SSL seems to be broken but it wasn't working before the patch anyways.

**Comment by samoht0** [comment]
> [...] If you make a pull request I'll accept it, or if you don't care I'll just commit the patched file.

I'm fine with commiting the the patch. Please do so.

**Comment by RhythmLunatic** [comment]
https://github.com/RhythmLunatic/xdccget/commit/a9500a7f70b848ff84134fa14730ef95ea6d5133
